apiVersion: v1
kind: Service
metadata:
  name: hacker-news-backend-svc
  labels:
    app: hacker-news-backend
spec:
  selector:
    app: hacker-news-backend
  ports:
    - protocol: TCP
      port: 80 # Port exposed by the service
      targetPort: 8000 # Port on the pods/containers
  type: LoadBalancer
